---
- hosts: all
  become: True

  roles:
  - { role: hostname }
# - { role: update }
  - { role: k8s-install }
  - { role: k8s-init, when: inventory_hostname in groups.masters and
                      first_run | bool == True, tags: ["init"] }
  - { role: calico, when: inventory_hostname in groups.masters and
                      first_run | bool == True, tags: ["calico"] }
# - { role: helm, when: inventory_hostname in groups.masters, tags: ["helm"] }

