---
- hosts: all
  become: True

  roles:
  - { role: hostname }
  - { role: update, when: first_run | d(False) | bool == True }
  - { role: k8s-install }
  - { role: k8s-init, when: inventory_hostname in groups.masters and
                      first_run | d(False) | bool == True, tags: ["init"] }
  - { role: calico, when: inventory_hostname in groups.masters and
                      first_run | d(False) | bool == True, tags: ["calico"] }
  - { role: helm, when: inventory_hostname in groups.masters and
                      first_run | d(False) | bool == True, tags: ["helm"] }

