---
- name: Update distro
  apt:
    upgrade: safe
    update_cache: True
  register: rg
  when: first_run | d(False) | bool

- name: Reboot
  reboot:
    reboot_timeout: 60
  when: first_run | d(False) | bool and rg.changed
