---
- name: Install requirements
  apt:
    name:
      - python-apt
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - curl
      - gnupg2
      - python-pip
      - python3-pip
      - nfs-common  # actully not required, just for my stand
      - iptables
      - arptables
      - ebtables
    update_cache: True
  register: requirements

- name: Switch to legacy versions
  command: "{{ item }}"
  with_items:
    - update-alternatives --set iptables /usr/sbin/iptables-legacy
    - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
    - update-alternatives --set arptables /usr/sbin/arptables-legacy
    - update-alternatives --set ebtables /usr/sbin/ebtables-legacy
  when: requirements.changed and ansible_distribution_release in nftables_distrs
  vars:
    nftables_distrs:
      - buster

- name: Add docker keys
  apt_key:
    keyserver: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
    filename: docker

- name: Add k8s keys
  apt_key:
    keyserver: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB

- name: Add repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes

- name: Install docker
  apt:
    name:
      - "docker-ce{{ '=' + docker_version if docker_version | d(False) else '' }}"
      - "docker-ce-cli{{ '=' + docker_version if docker_version | d(False) else '' }}"
      - "containerd.io{{ '=' + containerd_version if containerd_version | d(False) else '' }}"
    update_cache: True

- name: Copy docker config
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  register: docker_config

- name: Docker reload
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
  when: docker_config.changed

- name: Install k8s
  apt:
    name: "{{ k8s_packets }}"
    update_cache: True

- name: Hold packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
  - kubelet
  - kubeadm
  - kubectl
  - docker-ce
  - docker-ce-cli
  - containerd.io

